"""Bundle the apps/api/.venv into the Tauri externalBin directory.

Phase 3 Task 1.4 — embed the Python interpreter + sidecar venv into
the Tauri bundle so players do not need a system Python install.

Usage
-----

    # Dry-run (default in CI / when --dry-run is passed):
    #   - shows src → dst mapping
    #   - reports total size + file count
    #   - writes INSTALL.md into the target directory
    #   - does NOT copy anything
    python scripts/bundle_python.py --dry-run

    # Real copy (use only when shipping):
    #   - copies the whole venv (~500 MB) into the bundle
    #   - then INSTALL.md is written alongside
    python scripts/bundle_python.py

Inputs
------
- ``apps/api/.venv/`` — the existing uv-managed virtualenv.
  Contains ``Scripts/python.exe`` on Windows, ``bin/python`` on
  Linux, plus all wheels (biopython, pydantic, fastapi, llama-cpp,
  proto-language, ...).

Outputs
-------
- ``apps/desktop/src-tauri/binaries/python-bundle/`` — copied venv.
- ``apps/desktop/src-tauri/binaries/python-bundle/INSTALL.md`` —
  cross-platform path map for the Tauri runtime.

The destination matches ``bundle.externalBin[0] = "binaries/python-bundle/python"``
in ``apps/desktop/src-tauri/tauri.conf.json``.  Tauri resolves the
platform-specific extension automatically:

  - Windows: ``binaries/python-bundle/python.exe``
  - macOS:   ``binaries/python-bundle/python``
  - Linux:   ``binaries/python-bundle/bin/python``
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# Project root = parent of this script's parent (scripts/ lives at root).
PROJECT_ROOT = Path(__file__).resolve().parent.parent

SRC_VENV = PROJECT_ROOT / "apps" / "api" / ".venv"
DST_BUNDLE = PROJECT_ROOT / "apps" / "desktop" / "src-tauri" / "binaries" / "python-bundle"

INSTALL_MD = """# ProtoForge Python Bundle — INSTALL notes

This directory contains the **embedded Python interpreter + sidecar venv**
that ships with the ProtoForge desktop build (Tauri Phase 3, Task 1.4).

It is generated by ``scripts/bundle_python.py`` from ``apps/api/.venv``.

## Players never install Python

After ``pnpm tauri build`` produces the installer, players just double-click
``ProtoForge.exe`` (or ``.dmg`` / ``.AppImage``).  Tauri resolves the
``externalBin`` entry ``binaries/python-bundle/python`` to a platform
specific path:

| Platform | Resolved path (relative to install / game dir) |
| -------- | ---------------------------------------------- |
| Windows  | ``binaries/python-bundle/python.exe``          |
| macOS    | ``binaries/python-bundle/python``              |
| Linux    | ``binaries/python-bundle/bin/python``          |

The Rust sidecar launcher (``apps/desktop/src-tauri/src/sidecar.rs``)
spawns this binary with:

```
-m uvicorn app.main:app --port 7654 --host 127.0.0.1
```

so the desktop app talks to a fully-bundled FastAPI server.

## Layout

```
python-bundle/
├── INSTALL.md          # this file
├── python.exe          # Windows interpreter
├── Scripts/            # Windows entry-points (uvicorn, etc.)
├── Lib/site-packages/  # biopython, fastapi, llama-cpp, proto-language, ...
└── bin/                # Linux/macOS interpreter + symlinks
    └── python
```

## What lives inside

- ``proto-language`` (vendored under ``apps/api/vendor/proto-language``)
- ESM2 / SpliceAI / SpliceTransformer model loaders
- llama-cpp-python runtime (Qwen2.5-7B GGUF in the same bundle)
- fastapi / uvicorn / pydantic / sqlalchemy / aiosqlite

## Why this is huge (~500 MB)

The full ML stack (biopython, scipy, llama-cpp) cannot be slimmed down
without breaking the in-game experience.  We accept the size in
exchange for a zero-friction installer: the player should never see
a "Python not found" or "pip install biopython" dialog.

## Dev mode vs bundle mode

- **Dev mode** (``pnpm tauri dev``): the existing
  ``apps/desktop/src-tauri/src/sidecar.rs`` falls back to the system
  ``python`` (or ``$PROTOFORGE_PYTHON``) so devs can iterate on
  the API without rebuilding the bundle.
- **Bundle mode** (this directory): the same launcher prefers the
  embedded binary when present, then falls back to system Python.

## Regenerating

```
python scripts/bundle_python.py
```

Dry-run only (no copy, just report sizes + write INSTALL.md):

```
python scripts/bundle_python.py --dry-run
```
"""


def _humanize(n_bytes: int) -> str:
    """Return a human-readable byte count (KiB / MiB / GiB)."""
    units = ("B", "KiB", "MiB", "GiB", "TiB")
    size = float(n_bytes)
    for u in units:
        if size < 1024 or u == units[-1]:
            return f"{size:.2f} {u}" if u != "B" else f"{int(size)} B"
        size /= 1024
    return f"{size:.2f} TiB"


def _scan(src: Path) -> tuple[int, int, int]:
    """Walk ``src`` and return (file_count, dir_count, total_bytes)."""
    files = dirs = total = 0
    for p in src.rglob("*"):
        if p.is_file():
            files += 1
            try:
                total += p.stat().st_size
            except OSError:
                # Broken symlink or permission error — skip silently.
                pass
        elif p.is_dir():
            dirs += 1
    return files, dirs, total


def _resolve_dst_layout() -> dict[str, str]:
    """Cross-platform interpreter map (Tauri externalBin convention)."""
    return {
        "windows": "binaries/python-bundle/python.exe",
        "darwin": "binaries/python-bundle/python",
        "linux": "binaries/python-bundle/bin/python",
    }


def dry_run() -> int:
    """Report what *would* happen, write INSTALL.md, do not copy."""
    if not SRC_VENV.exists():
        print(f"[ERR] Source venv not found: {SRC_VENV}", file=sys.stderr)
        return 2

    files, dirs, total = _scan(SRC_VENV)
    layout = _resolve_dst_layout()

    print("=" * 60)
    print("ProtoForge Python bundler — DRY RUN")
    print("=" * 60)
    print(f"  source  : {SRC_VENV}")
    print(f"  dest    : {DST_BUNDLE}")
    print(f"  files   : {files:,}")
    print(f"  dirs    : {dirs:,}")
    print(f"  size    : {_humanize(total)} ({total:,} B)")
    print()
    print("  platform-specific interpreter paths Tauri will resolve:")
    for plat, p in layout.items():
        print(f"    {plat:<8} -> {p}")
    print()

    # Write INSTALL.md even in dry-run so downstream tests can verify it.
    DST_BUNDLE.mkdir(parents=True, exist_ok=True)
    install_path = DST_BUNDLE / "INSTALL.md"
    install_path.write_text(INSTALL_MD, encoding="utf-8")
    print(f"  wrote   : {install_path}")

    print()
    print("Run without --dry-run to perform the actual copy.")
    return 0


def copy_venv() -> int:
    """Copy the venv into the bundle directory and write INSTALL.md."""
    if not SRC_VENV.exists():
        print(f"[ERR] Source venv not found: {SRC_VENV}", file=sys.stderr)
        return 2

    DST_BUNDLE.mkdir(parents=True, exist_ok=True)

    print(f"Copying {SRC_VENV} -> {DST_BUNDLE} ...")
    # ``dirs_exist_ok=True`` so re-runs overwrite in place.
    shutil.copytree(SRC_VENV, DST_BUNDLE, dirs_exist_ok=True)

    (DST_BUNDLE / "INSTALL.md").write_text(INSTALL_MD, encoding="utf-8")
    print(f"Wrote {DST_BUNDLE / 'INSTALL.md'}")
    print("Done.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bundle apps/api/.venv into the Tauri externalBin directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="scan + report + write INSTALL.md, but do NOT copy venv contents",
    )
    args = parser.parse_args()
    return dry_run() if args.dry_run else copy_venv()


if __name__ == "__main__":
    sys.exit(main())
